"""Embed the SubSync icon in the VLC extension (descriptor().icon).

VLC reads an extension's icon from the PNG bytes in its descriptor, so the image
lives in subsync_ext.lua as an escaped Lua string between the ICON markers. VLC
scans extensions in a Lua state with no libraries at all (not even table.concat),
so the string is one chain of literals joined with `..`; Lua's parser recurses once
per operand (200 levels at most), hence the small icon. Re-run after changing
assets/icon-256.png:

    pip install pillow
    python scripts/embed_ext_icon.py
"""

from __future__ import annotations

import io
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "icon-256.png"
LUA = ROOT / "src" / "vlcsubsync" / "lua" / "extensions" / "subsync_ext.lua"
SIZE = 64  # the Active Extensions list draws it at about 40 px
WIDTH = 106  # escaped chars per source line (luacheck allows 120)
MAX_PARTS = 100  # operands of the `..` chain

BEGIN = "-- ICON BEGIN (generated by scripts/embed_ext_icon.py)\n"
END = "-- ICON END\n"


def png_bytes() -> bytes:
    img = Image.open(SRC).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def lua_escape(data: bytes) -> list[str]:
    """Chunks of a Lua string literal body (3-digit decimal escapes are valid in
    Lua 5.1+ and never swallow a following digit)."""
    out: list[str] = []
    cur = ""
    for b in data:
        c = chr(b) if 0x20 <= b < 0x7F and chr(b) not in '\\"' else f"\\{b:03d}"
        if len(cur) + len(c) > WIDTH:
            out.append(cur)
            cur = ""
        cur += c
    if cur:
        out.append(cur)
    return out


def main() -> None:
    parts = [f'"{chunk}"' for chunk in lua_escape(png_bytes())]
    if len(parts) > MAX_PARTS:
        raise SystemExit(f"icon too large: {len(parts)} string parts (max {MAX_PARTS})")
    body = " ..\n    ".join(parts)
    block = f"{BEGIN}local ICON_PNG =\n    {body}\n{END}"
    text = LUA.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + ".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"ICON markers not found in {LUA}")
    LUA.write_text(pattern.sub(lambda _m: block, text), encoding="utf-8")
    print(f"embedded {SIZE}px icon in {LUA.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
